// <auto-generated />
using System;
using Electric_Power_Monitoring_System.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Electric_Power_Monitoring_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430180443_AddUserHubAndRemoveHubUserId")]
    partial class AddUserHubAndRemoveHubUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Hub", b =>
                {
                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Serial");

                    b.ToTable("hubs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FcmResponse")
                        .HasColumnType("text")
                        .HasColumnName("fcm_response");

                    b.Property<string>("HubSerial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HubSerial");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_notifications_sent_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_notifications_user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.HasKey("Id");

                    b.HasIndex("HubSerial", "PlugNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_plugs_hub_serial_plug_number");

                    b.ToTable("plugs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CumulativeEnergyWh")
                        .HasColumnType("numeric")
                        .HasColumnName("cumulative_energy_wh");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<long?>("PlugId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PlugId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_readings_timestamp");

                    b.HasIndex("HubSerial", "PlugNumber", "Timestamp")
                        .HasDatabaseName("IX_readings_hub_plug_timestamp");

                    b.ToTable("readings");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.HasIndex("UserIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_users_user_identifier");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .HasDatabaseName("IX_user_devices_fcm_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_devices_user_id");

                    b.ToTable("user_devices");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserHub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier", "HubSerial")
                        .IsUnique()
                        .HasDatabaseName("IX_user_hubs_user_hub");

                    b.ToTable("user_hubs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Notification", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany()
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany("Plugs")
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Reading", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany("Readings")
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electric_Power_Monitoring_System.Models.Plug", null)
                        .WithMany("Readings")
                        .HasForeignKey("PlugId");

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Hub", b =>
                {
                    b.Navigation("Plugs");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
