// <auto-generated />
using System;
using Electric_Power_Monitoring_System.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Electric_Power_Monitoring_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714124758_sssss")]
    partial class sssss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.AbnormalConsumptionTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DailyConsumptionWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("daily_consumption_wh");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<DateTime?>("LastAlertDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_alert_date");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_date");

                    b.Property<int>("Stage")
                        .HasColumnType("integer")
                        .HasColumnName("stage");

                    b.Property<DateTime?>("StageStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stage_start_date");

                    b.HasKey("Id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("IX_abnormal_tracking_stage");

                    b.HasIndex("HubSerial", "PlugNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_abnormal_tracking_hub_plug");

                    b.ToTable("abnormal_consumption_tracking");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.AiTipsCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("TipText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tip_text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("ai_tips_cache");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            TipText = "أطفئ الأجهزة غير المستخدمة من الفيشة لتوفير الكهرباء.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            TipText = "استخدم لمبات LED بدلاً من اللمبات العادية.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            TipText = "اضبط درجة حرارة الثلاجة على المستوى المتوسط.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            TipText = "شغل الغسالة والغسالة الأطباق في أوقات الذروة المنخفضة (بعد 10 مساءً).",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            TipText = "قلل من استخدام المكواة الكهربائية أو استخدمها لفترات قصيرة.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            TipText = "استخدم سخان المياه الشمسي بدلاً من الكهربائي.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            TipText = "افصل شاحن الهاتف بعد شحن البطارية.",
                            Type = "tier"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            TipText = "افحص باب الثلاجة للتأكد من إغلاقه بإحكام.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            TipText = "نظف المكثف الخلفي للثلاجة من الأتربة.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            TipText = "تأكد من عدم وجود تسريب في غاز التبريد.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            TipText = "افحص منظم الحرارة واضبطه على درجة حرارة مناسبة.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            TipText = "تأكد من عدم وجود ثلج متراكم داخل الفريزر.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            TipText = "افصل الثلاجة لمدة ساعة ثم أعد تشغيلها.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            TipText = "تأكد من عدم وجود فجوات في عازل الباب.",
                            Type = "abnormal"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            TipText = "قم بقياس درجة الحرارة داخل الثلاجة للتأكد من أنها مناسبة.",
                            Type = "abnormal"
                        });
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.DeviceBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaselineWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("baseline_wh");

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_date");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.HasKey("Id");

                    b.HasIndex("HubSerial", "PlugNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_device_baseline_hub_plug");

                    b.ToTable("device_baseline");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Hub", b =>
                {
                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Serial");

                    b.ToTable("hubs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.LightingEstimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("actual_wh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<decimal>("EstimatedWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("estimated_wh");

                    b.Property<bool>("IsCorrected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_corrected");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier", "Year", "Month", "Day")
                        .IsUnique()
                        .HasDatabaseName("IX_lighting_estimates_user_year_month_day");

                    b.ToTable("lighting_estimates");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BalanceEgp")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("balance_egp");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reading_date");

                    b.Property<decimal>("ReadingValueWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("reading_value_wh");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier", "Year", "Month")
                        .HasDatabaseName("IX_meter_readings_user_year_month");

                    b.ToTable("meter_readings");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FcmResponse")
                        .HasColumnType("text")
                        .HasColumnName("fcm_response");

                    b.Property<string>("HubSerial")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("HubSerial");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_notifications_sent_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_notifications_user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.HasKey("Id");

                    b.HasIndex("HubSerial", "PlugNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_plugs_hub_serial_plug_number");

                    b.ToTable("plugs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CumulativeEnergyWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cumulative_energy_wh");

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<long?>("PlugId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlugNumber")
                        .HasColumnType("integer")
                        .HasColumnName("plug_number");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PlugId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_readings_timestamp");

                    b.HasIndex("HubSerial", "PlugNumber", "Timestamp")
                        .HasDatabaseName("IX_readings_hub_plug_timestamp");

                    b.ToTable("readings");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.TierNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<decimal>("NextTierPrice")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("next_tier_price");

                    b.Property<decimal>("RemainingKWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("remaining_kwh");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("TipsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tips");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_tier_notifications_sent_at");

                    b.HasIndex("UserIdentifier")
                        .HasDatabaseName("IX_tier_notifications_user");

                    b.ToTable("tier_notifications");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.TierSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxKWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("max_kwh");

                    b.Property<decimal>("MinKWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("min_kwh");

                    b.Property<decimal>("PricePerKWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("price_per_kwh");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tier_name");

                    b.HasKey("Id");

                    b.ToTable("tier_settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxKWh = 50m,
                            MinKWh = 0m,
                            PricePerKWh = 0.68m,
                            TierName = "شريحة 1"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxKWh = 100m,
                            MinKWh = 51m,
                            PricePerKWh = 0.78m,
                            TierName = "شريحة 2"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaxKWh = 200m,
                            MinKWh = 101m,
                            PricePerKWh = 0.95m,
                            TierName = "شريحة 3"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MaxKWh = 350m,
                            MinKWh = 201m,
                            PricePerKWh = 1.20m,
                            TierName = "شريحة 4"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MaxKWh = 650m,
                            MinKWh = 351m,
                            PricePerKWh = 1.45m,
                            TierName = "شريحة 5"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MaxKWh = 1000m,
                            MinKWh = 651m,
                            PricePerKWh = 1.60m,
                            TierName = "شريحة 6"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MaxKWh = 79228162514264337593543950335m,
                            MinKWh = 1001m,
                            PricePerKWh = 1.85m,
                            TierName = "شريحة 7"
                        });
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.HasIndex("UserIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_users_user_identifier");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserConsumptionTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CumulativeConsumptionWh")
                        .HasPrecision(20, 10)
                        .HasColumnType("numeric(20,10)")
                        .HasColumnName("cumulative_consumption_wh");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("IX_user_consumption_tracking_user_year_month");

                    b.ToTable("user_consumption_tracking");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .HasDatabaseName("IX_user_devices_fcm_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_devices_user_id");

                    b.ToTable("user_devices");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserHub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("HubSerial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_serial");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier", "HubSerial")
                        .IsUnique()
                        .HasDatabaseName("IX_user_hubs_user_hub");

                    b.ToTable("user_hubs");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.UserMandatoryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier")
                        .IsUnique()
                        .HasDatabaseName("IX_user_mandatory_state_user");

                    b.ToTable("user_mandatory_state");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Notification", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany()
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany("Plugs")
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Reading", b =>
                {
                    b.HasOne("Electric_Power_Monitoring_System.Models.Hub", "Hub")
                        .WithMany("Readings")
                        .HasForeignKey("HubSerial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electric_Power_Monitoring_System.Models.Plug", null)
                        .WithMany("Readings")
                        .HasForeignKey("PlugId");

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Hub", b =>
                {
                    b.Navigation("Plugs");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("Electric_Power_Monitoring_System.Models.Plug", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
